services:
  portainer:
      image: portainer/portainer-ce:2.27.6
      container_name: portainer
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - portainer-data:/data
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
        - "traefik.http.routers.portainer.entrypoints=web"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      networks:
        - traefik


volumes:
  portainer-data:

networks:
  traefik:
    name: traefik-net
    external: true
    