services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_pass
      MINIO_BROWSER_REDIRECT_URL: http://minio.localhost
    volumes:
      - minio-data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.localhost`)
      - traefik.http.routers.minio.entrypoints=web
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9001
      - traefik.http.routers.minio-api.rule=Host(`minio-api.localhost`)
      - traefik.http.routers.minio-api.entrypoints=web
      - traefik.http.routers.minio-api.service=minio-api
      - traefik.http.services.minio-api.loadbalancer.server.port=9000
    restart: unless-stopped
    networks:
      - traefik
    command: server /data --console-address ":9001" --address ":9000"

volumes:
  minio-data:

networks:
  traefik:
    name: traefik-net
    external: true